name: Upload documentation

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish-ghp:
    name: Upload documentation to GH Pages
    runs-on: ubuntu-latest
    environment: Documentation
    permissions:
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Build Book
        run: |
          cd docs
          mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/book"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
